"""agrega boards (tablero de analisis)

Revision ID: 3665445db37f
Revises: c2f6f3e3197a
Create Date: 2026-09-06 13:04:39.842394

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3665445db37f"
down_revision: str | Sequence[str] | None = "c2f6f3e3197a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=True),
        sa.Column("root_fen", sa.String(), nullable=False),
        sa.Column("tree_json", sa.JSON(), nullable=False),
        sa.Column("is_own_game", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boards")
    # ### end Alembic commands ###
