"""agrega engine_settings editable

Revision ID: 559f3a27ec5c
Revises: 5bd605e0780c
Create Date: 2026-09-06 12:31:53.075165

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "559f3a27ec5c"
down_revision: str | Sequence[str] | None = "5bd605e0780c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engine_settings",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("threads", sa.Integer(), nullable=False),
        sa.Column("hash_mb", sa.Integer(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("multipv", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("engine_settings")
    # ### end Alembic commands ###
