"""agrega analyses, analyzed_moves y position_cache

Revision ID: 5bd605e0780c
Revises: ba635b1b246e
Create Date: 2026-09-05 18:25:36.574778

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bd605e0780c"
down_revision: str | Sequence[str] | None = "ba635b1b246e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position_cache",
        sa.Column("fen", sa.String(), nullable=False),
        sa.Column("engine", sa.String(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("multipv", sa.Integer(), nullable=False),
        sa.Column("lines_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("fen", "engine", "depth", "multipv"),
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("engine", sa.String(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("multipv", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("white_accuracy", sa.Float(), nullable=True),
        sa.Column("black_accuracy", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyzed_moves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("ply", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("san", sa.String(), nullable=False),
        sa.Column("uci", sa.String(), nullable=False),
        sa.Column("fen_before", sa.String(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("move_accuracy", sa.Float(), nullable=False),
        sa.Column("win_percent_before", sa.Float(), nullable=False),
        sa.Column("win_percent_after", sa.Float(), nullable=False),
        sa.Column("best_move_uci", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analyzed_moves")
    op.drop_table("analyses")
    op.drop_table("position_cache")
    # ### end Alembic commands ###
