"""agrega board_versions (deshacer y rehacer)

El historial de un tablero de análisis (RF-6.8): cada estado por el que pasó,
con su árbol entero y su `root_fen` —importar un PGN puede mover la raíz,
RF-6.7—, y `boards.current_version_id` como cursor de por dónde va el
deshacer. Es lineal y persistido a propósito (ADR-0012); el cursor no lleva
clave foránea porque declarar las dos direcciones deja un ciclo de tablas que
SQLite no sabe romper.

Los tableros que ya existen se quedan sin versiones y con el cursor en nulo,
sin migrar nada: su primera edición anota la versión inicial, así que en
ellos lo único que no se podrá deshacer es esa primera edición.

Revision ID: 97d2b0821d2b
Revises: b4e8c17f0a92
Create Date: 2026-09-18 13:35:39.107566

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97d2b0821d2b"
down_revision: str | Sequence[str] | None = "b4e8c17f0a92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("root_fen", sa.String(), nullable=False),
        sa.Column("tree_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("boards", sa.Column("current_version_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boards", "current_version_id")
    op.drop_table("board_versions")
    # ### end Alembic commands ###
