"""agrega country y joined_at a players

Revision ID: ba635b1b246e
Revises: bb48c0b0a1f0
Create Date: 2026-09-05 17:59:58.428951

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba635b1b246e"
down_revision: str | Sequence[str] | None = "bb48c0b0a1f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("country", sa.String(), nullable=True))
    op.add_column("players", sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "joined_at")
    op.drop_column("players", "country")
    # ### end Alembic commands ###
