"""esquema inicial: players, games, sync_state

Revision ID: bb48c0b0a1f0
Revises:
Create Date: 2026-09-05 17:50:30.867847

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb48c0b0a1f0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("ratings_json", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "username", name="uq_player_platform_username"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("platform_id", sa.String(), nullable=False),
        sa.Column("pgn", sa.String(), nullable=False),
        sa.Column("white_username", sa.String(), nullable=False),
        sa.Column("white_rating", sa.Integer(), nullable=False),
        sa.Column("white_result", sa.String(), nullable=False),
        sa.Column("black_username", sa.String(), nullable=False),
        sa.Column("black_rating", sa.Integer(), nullable=False),
        sa.Column("black_result", sa.String(), nullable=False),
        sa.Column("time_control", sa.String(), nullable=False),
        sa.Column("time_class", sa.String(), nullable=False),
        sa.Column("rules", sa.String(), nullable=False),
        sa.Column("rated", sa.Boolean(), nullable=False),
        sa.Column("eco", sa.String(), nullable=True),
        sa.Column("clocks_json", sa.JSON(), nullable=True),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "platform_id", name="uq_game_platform_platform_id"),
    )
    op.create_table(
        "sync_state",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("last_synced_year", sa.Integer(), nullable=False),
        sa.Column("last_synced_month", sa.Integer(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_state")
    op.drop_table("games")
    op.drop_table("players")
    # ### end Alembic commands ###
