"""agrega phase a analyzed_moves

Revision ID: c2f6f3e3197a
Revises: 559f3a27ec5c
Create Date: 2026-09-06 12:59:38.261338

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2f6f3e3197a"
down_revision: str | Sequence[str] | None = "559f3a27ec5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default` es necesario: SQLite rechaza añadir una columna NOT NULL
    # a una tabla existente si no sabe con qué rellenar las filas que ya hay.
    # Los análisis anteriores a esta migración quedan como "middlegame"; se
    # corrigen volviendo a analizar la partida.
    op.add_column(
        "analyzed_moves",
        sa.Column("phase", sa.String(), nullable=False, server_default="middlegame"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyzed_moves", "phase")
    # ### end Alembic commands ###
